export const TYPEOF_TRANSPORT = {
  ALL: "all",
  PASSENGER: "passenger",
  MOTO: "moto",
  TRUCK: "truck",
  SPECIAL: "special",
  BUS: "bus",
} as const;

export const TYPES_OF_TRANSPORT = [
  { value: TYPEOF_TRANSPORT.ALL, label: "Все" },
  { value: TYPEOF_TRANSPORT.PASSENGER, label: "Легкові" },
  { value: TYPEOF_TRANSPORT.MOTO, label: "Мото" },
  { value: TYPEOF_TRANSPORT.TRUCK, label: "Вантажівки" },
  { value: TYPEOF_TRANSPORT.SPECIAL, label: "Спецтехніка" },
  { value: TYPEOF_TRANSPORT.BUS, label: "Автобуси" },
];

export const CAR_BRANDS = [
  { value: "acura", label: "Acura" },
  { value: "alfa-romeo", label: "Alfa Romeo" },
  { value: "aston-martin", label: "Aston Martin" },
  { value: "audi", label: "Audi" },
  { value: "bentley", label: "Bentley" },
  { value: "bmw", label: "BMW" },
  { value: "bugatti", label: "Bugatti" },
  { value: "buick", label: "Buick" },
  { value: "cadillac", label: "Cadillac" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "chrysler", label: "Chrysler" },
  { value: "citroen", label: "Citroën" },
  { value: "cupra", label: "Cupra" },
  { value: "dacia", label: "Dacia" },
  { value: "daewoo", label: "Daewoo" },
  { value: "daihatsu", label: "Daihatsu" },
  { value: "dodge", label: "Dodge" },
  { value: "ds", label: "DS Automobiles" },
  { value: "ferrari", label: "Ferrari" },
  { value: "fiat", label: "Fiat" },
  { value: "ford", label: "Ford" },
  { value: "genesis", label: "Genesis" },
  { value: "gmc", label: "GMC" },
  { value: "great-wall", label: "Great Wall" },
  { value: "haval", label: "Haval" },
  { value: "honda", label: "Honda" },
  { value: "hyundai", label: "Hyundai" },
  { value: "infiniti", label: "Infiniti" },
  { value: "isuzu", label: "Isuzu" },
  { value: "jaguar", label: "Jaguar" },
  { value: "jeep", label: "Jeep" },
  { value: "kia", label: "Kia" },
  { value: "koenigsegg", label: "Koenigsegg" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "lancia", label: "Lancia" },
  { value: "land-rover", label: "Land Rover" },
  { value: "lexus", label: "Lexus" },
  { value: "lincoln", label: "Lincoln" },
  { value: "lotus", label: "Lotus" },
  { value: "lucid", label: "Lucid" },
  { value: "maserati", label: "Maserati" },
  { value: "maybach", label: "Maybach" },
  { value: "mazda", label: "Mazda" },
  { value: "mclaren", label: "McLaren" },
  { value: "mercedes-benz", label: "Mercedes-Benz" },
  { value: "mg", label: "MG" },
  { value: "mini", label: "MINI" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "nissan", label: "Nissan" },
  { value: "opel", label: "Opel" },
  { value: "peugeot", label: "Peugeot" },
  { value: "polestar", label: "Polestar" },
  { value: "pontiac", label: "Pontiac" },
  { value: "porsche", label: "Porsche" },
  { value: "ram", label: "RAM" },
  { value: "renault", label: "Renault" },
  { value: "rolls-royce", label: "Rolls-Royce" },
  { value: "rover", label: "Rover" },
  { value: "saab", label: "Saab" },
  { value: "seat", label: "SEAT" },
  { value: "skoda", label: "Skoda" },
  { value: "smart", label: "Smart" },
  { value: "subaru", label: "Subaru" },
  { value: "suzuki", label: "Suzuki" },
  { value: "tesla", label: "Tesla" },
  { value: "toyota", label: "Toyota" },
  { value: "vinfast", label: "VinFast" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "volvo", label: "Volvo" },
  { value: "xpeng", label: "Xpeng" },
  { value: "zhidou", label: "Zhidou" },
];

export const CAR_CONDITION = {
  ALL: "all",
  NEW: "new",
  USED: "used",
} as const;

export const CAR_CONDITION_FILTERS = [
  { value: CAR_CONDITION.ALL, label: "Всі" },
  { value: CAR_CONDITION.NEW, label: "Нові" },
  { value: CAR_CONDITION.USED, label: "Вживані" },
];

export const CAR_ACCIDENT = {
  ALL: "all",
  YES: "yes",
  NO: "no",
} as const;

export const CAR_ACCIDENT_FILTERS = [
  { value: CAR_ACCIDENT.ALL, label: "Всі" },
  { value: CAR_ACCIDENT.YES, label: "Було" },
  { value: CAR_ACCIDENT.NO, label: "Не було" },
];
